#:schema http://rise.local:3000/api/v1/schema/rise-toml/v1
version = 1

[project]
name = "hello-world-py"
access_class = "private"
custom_domains = []

[project.env]

[build]
backend = "railpack"

# [registry]
# image_base = "jfrog.helsing-dev.ai/hdf-docker-playground/hs-hdf-rise-apps"
