apiVersion: v2
name: chart
description: A Helm chart for Rise - a Kubernetes deployment platform
type: application
version: 0.23.0-rc8
appVersion: "0.23.0-rc8"
keywords:
  - kubernetes
  - deployment
  - paas
home: https://github.com/rise-deploy/rise
sources:
  - https://github.com/rise-deploy/rise
dependencies:
  - name: metacontroller-helm
    version: "4.17.2"
    repository: "oci://ghcr.io/metacontroller"
    alias: metacontroller-operator
    condition: metacontroller.install
  - name: loki
    version: "6.55.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: logs.loki.enabled
  - name: alloy
    version: "1.11.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: logs.alloy.enabled
