apiVersion: v2
name: rise
description: A Helm chart for Rise - a Kubernetes deployment platform
type: application
version: 0.22.1
appVersion: "0.22.1"
keywords:
  - kubernetes
  - deployment
  - paas
home: https://github.com/rise-deploy/rise
sources:
  - https://github.com/rise-deploy/rise
dependencies:
  - name: metacontroller-helm
    version: "4.15.0"
    repository: "oci://ghcr.io/metacontroller"
    alias: metacontroller-operator
    condition: metacontroller.install
