apiVersion: v2
name: rise
description: A Helm chart for Rise - a Kubernetes deployment platform
type: application
version: 0.21.1
appVersion: "0.21.1"
keywords:
  - kubernetes
  - deployment
  - paas
home: https://github.com/niklasrosenstein/rise
sources:
  - https://github.com/niklasrosenstein/rise
dependencies:
  - name: metacontroller-helm
    version: "4.15.0"
    repository: "oci://ghcr.io/metacontroller"
    alias: metacontroller-operator
    condition: metacontroller.install
